#!/bin/bash

# script written to already include multiple checks and not fail at the first one
everythingOK=true

# linting some tex files (as defined in Makefile, usually with chktex)
tmpString="$(make lint_tex)"
if [ "$?" -ne 0 ]; then
	echo ":::::::::::::::::::::::::"
	echo "the tex linter chktex encountered the following error"
	echo ":::::::::::::::::::::::::"
	echo "$tmpString"
	everythingOK=false
fi

# linting the bib file (defined in Makefile)
tmpString="$(make lint_bib)"
if [ "$?" -ne 0 ]; then
	echo ":::::::::::::::::::::::::"
	echo "the bib linter encountered the following error"
	echo ":::::::::::::::::::::::::"
	echo "$tmpString"
	everythingOK=false
fi


if ! $everythingOK; then
	echo ":::::::::::::::::::::::::"
	echo "there was an error, if you want to commit nonetheless use 'git commit --no-verify'"
	exit 1
fi
