name: create archive for arxiv submission

on:
  workflow_dispatch:

jobs:
  buildPython:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Make the plots
        run: |
          make fig_python
      - name: 'Upload PDFs as artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: compiledFigPDFs
          path: fig/*.pdf
  buildPdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # only run after python figures are done
    needs: buildPython
    container:
      image: danteev/texlive

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
      # download archived fig pdfs
      - uses: actions/download-artifact@v2
        with:
          name: compiledFigPDFs
          path: fig/

      # compile pdf (also pure tikz figures)
      - name: LaTeX compilation from makefile
        run: make

      - name: 'Upload main PDF as artifact'
        uses: actions/upload-artifact@v2
        with:
          name: compiledPDF
          path: |
            fig_tikz/**/*.pdf
            main.pdf
  create_arxiv:
    runs-on: ubuntu-latest
    needs: buildPdf
    container:
      image: danteev/texlive
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install arxiv-collector
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade arxiv-collector
      - uses: actions/download-artifact@v2
        with:
          name: compiledFigPDFs
          path: fig/
      - name: create tarball
        run: |
          make
          arxiv-collector main.tex
      - name: 'Upload tarball as artifact'
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: |
            arxiv.tar.gz
